# Site settings
title: Shout to Me iOS SDK
email: support@shoutto.me
description: > # this means to ignore newlines until "baseurl:"
  The Shout to Me iOS SDK Documentation provides information, reference,
  and examples of how to incorporate Shout to Me platform functionality into
  your iOS app.
baseurl: "/stm-sdk-ios" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shout_to_me
github_username: ShoutToMe

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
